### ISSUE TITLE
Decide on smart contract platform

### ISSUE THREAD

**Issue by matresstester** [deadmenswitch/research#3]
I'm planning on using Ethereum, not having other ideas at the moment.

**Comment by gfnord** [comment]
We can run our project on testrpc, it's a fake backend for ethereum blockchain.

To install testrpc use the following command:
`npm install -g ethereumjs-testrpc`

And use solidity language to program on top of it.

**Comment by matresstester** [comment]
Bassem shared this project from his past hackathon

https://github.com/ScottStevenson/EthContractBuilder

**Comment by matresstester** [comment]
Definitely doing Ethereum
