### ISSUE TITLE
Decide on front end platform

### ISSUE THREAD

**Issue by matresstester** [deadmenswitch/research#4]
Will it be web based? or will it be Electron based desktop tool?

**Comment by gfnord** [comment]
To create and dApp, I've seen a lot of people using React.js.

https://reactjs.org/

Here is the installation instructions: https://reactjs.org/docs/installation.html

React has a lot of templates that a lot of common stuff comes ready to use.

**Comment by alex-precosky** [comment]
I just learned what a dApp is https://ethereum.stackexchange.com/questions/383/what-is-a-dapp

**Comment by matresstester** [comment]
Use truffle.js
